### ISSUE TITLE
Y'all got any more of them "Tests"?

### ISSUE THREAD

**Issue by jdrago999** [github/github-graphql-rails-example#7]
Hey -

Thanks for putting this example out there, and sharing it with the world.

However, next thing that will happen is we'll want to know how to test it.

How about a simple example? RSpec would be nice. Anything you've got can be expanded upon by us.

Thanks!

**Comment by josh** [comment]
> However, next thing that will happen is we'll want to know how to test it.

Standard Rails controllers tests using MiniTest or Rspec should just work fine, nothing really special. I'd probably suggest using some sort of HTTP mocking library.

You could also consider replacing the [`HTTPAdapter` here](https://github.com/github/github-graphql-rails-example/blob/d217dc62df61607f9820cfe28c079c17641dd68b/config/application.rb#L31) with `TestAdapter`.

* https://github.com/bblimke/webmock
* https://github.com/lostisland/faraday#using-faraday-for-testing
* https://robots.thoughtbot.com/how-to-stub-external-services-in-tests
